Repository whitneyburton/gameflix, pull requests merged in 2018-12, with the labels that each got.

#10 Add dynamic carousel by genre
  src/App.css
  src/App.js
  src/Components/Carousel/Carousel.css
  src/Components/Carousel/index.js
  src/Components/Featured/Featured.css
  src/Components/Featured/index.js
  src/Components/Navbar/Navbar.css
Labels: in progress

#16 WIP: SearchPage, search input, and delete cards
  public/favicon.ico
  public/img/test.jpg
  src/App.js
  src/Components/Carousel/index.js
  src/Components/Featured/index.js
  src/Components/LandingPage/LandingPage.css
  src/Components/LandingPage/index.js
  src/Components/Navbar/Navbar.css
  src/Components/Navbar/index.js
  src/Components/Popup/index.js
  src/Components/SearchPage/SearchPage.css
  src/Components/SearchPage/index.js
  src/Tests/__snapshots__/Carousel.test.js.snap
  src/Tests/__snapshots__/Featured.test.js.snap
  src/Tests/__snapshots__/LandingPage.test.js.snap
  src/Tests/__snapshots__/PopUp.test.js.snap
Labels: in progress

#17 Add youtube autoplay
  src/App.css
  src/Components/Featured/Featured.css
  src/Components/Featured/index.js
  src/Components/LandingPage/LandingPage.css
  src/Components/Navbar/Navbar.css
  src/Components/SearchPage/SearchPage.css
  src/index.css
Labels: P3, in progress

#21 Restructure files for scss
  package-lock.json
  package.json
  src/App.js
  src/Components/Carousel.js
  src/Components/Featured.js
  src/Components/GameCard.js
  src/Components/LandingPage.js
  src/Components/Navbar.js
  src/Components/PopUp.js
  src/Components/SearchPage.js
  src/styles/Main.scss
  src/styles/_App.scss
  src/styles/_Carousel.scss
  src/styles/_Featured.scss
  src/styles/_LandingPage.scss
  src/styles/_Navbar.scss
  src/styles/_PopUp.scss
  src/styles/_SearchPage.scss
Labels: P1, in progress

#23 Add popup details
  src/Components/Navbar.js
  src/Components/PopUp.js
  src/Tests/__snapshots__/Carousel.test.js.snap
  src/Tests/__snapshots__/Featured.test.js.snap
  src/Tests/__snapshots__/LandingPage.test.js.snap
  src/Tests/__snapshots__/PopUp.test.js.snap
  src/styles/_Carousel.scss
  src/styles/_Navbar.scss
  src/styles/_PopUp.scss
  src/styles/_SearchPage.scss
Labels: in progress

#25 Add logic for carousel scroll btns
  src/Components/Carousel.js
Labels: P1, in progress, user story

#26 WIP: CSS Styling and NavBar
  public/index.html
  src/Components/Carousel.js
  src/Components/GameCard.js
  src/Components/Navbar.js
  src/Components/PopUp.js
  src/styles/_Carousel.scss
  src/styles/_Navbar.scss
  src/styles/_PopUp.scss
Labels: in progress

#27 Add open animation to carousel popup
  src/App.js
  src/Components/GameCard.js
  src/Components/LandingPage.js
  src/Components/PopUp.js
  src/styles/_Carousel.scss
  src/styles/_PopUp.scss
Labels: in progress

#28 WIP start advancedFilter logic
  src/App.js
  src/Components/AdvancedSearch.js
  src/Components/Navbar.js
Labels: in progress
